export enum ArticlesActionTypes {
    FETCH_ARTICLE_START = 'FETCH_ARTICLE_START',
    FETCH_ARTICLE_SUCCESS = 'FETCH_ARTICLE_SUCCESS',
    FETCH_ARTICLE_ERROR = 'FETCH_ARTICLE_ERROR',
    FETCH_ARTICLE_BY_SLUG_SUCCESS = 'FETCH_ARTICLE_BY_SLUG_SUCCESS',
    PAGINATION_MULTI = 'PAGINATION_MULTI',

}
